### PR TITLE
Config option and function for updating existing Moodle accounts during sync.

### PR DESCRIPTION
**Pull request by pdmc78**
This pull request adds a configuration option and function for updating users during a synchronisation.

### CODE REVIEW

**Comment by nimojg-microsoft** [comment]
@pdmc78 Thanks so much for your contribution. Can we ask that you please make the pull request against the https://github.com/Microsoft/moodle-local_o365/ repo instead of the individual plugin repo? @jamesmcq FYI

**Comment by pdmc78** [comment]
HI @nimojg-microsoft sorry, would you like me to make the pull request into the Master branch (of moodle-local-o365) and not the Microsoft:MOODLE_31_STABLE branch?

**Comment by nimojg-microsoft** [comment]
@jamesmcq  which would you prefer?

**Comment by jamesmcq** [comment]
@pdmc78  Thanks for the PR! This has been reviewed and will be released shortly.

**Pull request closed without merging**
